# Generated by Django 4.2.10 on 2024-04-21 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Z2HUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_password_updated', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('login_mode', models.CharField(choices=[('web', 'web'), ('mobile', 'mobile')], default='mobile', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Z2HCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('active_plan_uid', models.CharField(max_length=64)),
                ('plan_start_date', models.DateField()),
                ('plan_end_date', models.DateField()),
                ('is_level_one_completed', models.BooleanField(default=False)),
                ('is_level_two_completed', models.BooleanField(default=False)),
                ('is_level_three_completed', models.BooleanField(default=False)),
                ('is_level_four_completed', models.BooleanField(default=False)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='user.z2hcustomers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('nominee_name', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(choices=[('single', 'single'), ('married', 'married')], max_length=64)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=64)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_number', models.CharField(max_length=64, unique=True)),
                ('city', models.CharField(max_length=128)),
                ('town', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('pin_code', models.CharField(max_length=6)),
                ('name_of_bank', models.CharField(max_length=128)),
                ('name_as_in_bank', models.CharField(max_length=256)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('bank_branch', models.CharField(max_length=128)),
                ('account_number', models.CharField(max_length=64)),
                ('profile_photo_path', models.CharField(blank=True, max_length=256, null=True)),
                ('email_address', models.CharField(max_length=256)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='utils.district')),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='user.z2hcustomers')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='user.role')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
