# Generated by Django 4.2.10 on 2024-03-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='z2huser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
