# Generated by Django 4.2.10 on 2024-04-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_z2hcustomers_plan_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='z2huser',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
