# Generated by Django 4.2.10 on 2024-03-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('user', '0003_registeruser_bank_branch_alter_registeruser_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='district',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='district',
            field=models.ManyToManyField(related_name='users', to='utils.district'),
        ),
    ]
