# Generated by Django 4.2.10 on 2024-03-16 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('user', '0004_remove_registeruser_district_registeruser_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='district',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='utils.district'),
            preserve_default=False,
        ),
    ]
