# Generated by Django 4.2.10 on 2024-05-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_z2huserroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='alternate_mobile_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
