# Generated by Django 4.2.10 on 2024-03-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_registeruser_is_active_registeruser_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='profile_photo_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
