# Generated by Django 4.2.10 on 2024-05-04 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_registeruser_alternate_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='user.z2hcustomers'),
        ),
    ]
