# Generated by Django 4.2.10 on 2024-03-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_registeruser_profile_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='z2huser',
            name='is_password_updated',
            field=models.BooleanField(default=False),
        ),
    ]
