# Generated by Django 4.2.10 on 2024-05-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_registeruser_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='z2hcustomers',
            name='is_admin_user',
            field=models.BooleanField(default=False),
        ),
    ]
