# Generated by Django 4.2.10 on 2024-05-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_z2hcustomers_is_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='z2hcustomers',
            name='is_level_four_commission_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='is_level_one_commission_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='is_level_three_commission_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='is_level_two_commission_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='level_four_commission_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='level_four_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='level_one_commission_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='level_one_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='level_three_commission_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='level_three_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='level_two_commission_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='level_two_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
