# Generated by Django 4.2.10 on 2024-04-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_z2huser_is_password_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='town',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
