# Generated by Django 4.2.10 on 2024-04-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_registeruser_address_registeruser_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='present_address',
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='city',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='town',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
