# Generated by Django 4.2.10 on 2024-05-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_z2hcustomers_is_level_four_commission_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='marital_status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced'), ('widowed', 'widowed')], max_length=64),
        ),
    ]
