# Generated by Django 4.2.10 on 2024-04-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_registeruser_present_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='email_address',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
