# Generated by Django 4.2.10 on 2024-05-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_registeruser_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='z2hcustomers',
            name='customer_number',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
