# Generated by Django 4.2.10 on 2024-05-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_z2hcustomers_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='is_admin_user',
            field=models.BooleanField(default=False),
        ),
    ]
