# Generated by Django 4.2.13 on 2024-06-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_z2hcustomers_level_four_commission_paid_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
