# Generated by Django 4.2.13 on 2024-06-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_registeruser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='z2hcustomers',
            name='is_level_four_payment_issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='is_level_one_payment_issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='is_level_three_payment_issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='is_level_two_payment_issue',
            field=models.BooleanField(default=False),
        ),
    ]
