# Generated by Django 4.2.13 on 2024-08-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_z2hcustomers_is_level_four_payment_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='is_referrer_got_notified_for_joining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='is_referrer_got_notified_for_joined_level_one',
            field=models.BooleanField(default=False),
        ),
    ]
