# Generated by Django 4.2.13 on 2024-08-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_registeruser_is_referrer_got_notified_for_joining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='z2hcustomers',
            name='is_referrer_got_notified_for_level_four_completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='is_referrer_got_notified_for_level_one_completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='is_referrer_got_notified_for_level_three_completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='is_referrer_got_notified_for_level_two_completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='is_user_got_notified_for_level_four_commission_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='is_user_got_notified_for_level_one_commission_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='is_user_got_notified_for_level_three_commission_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='z2hcustomers',
            name='is_user_got_notified_for_level_two_commission_paid',
            field=models.BooleanField(default=False),
        ),
    ]
