# Generated by Django 4.2.13 on 2024-08-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_z2hcustomers_is_referrer_got_notified_for_level_four_completion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='z2hcustomers',
            old_name='is_referrer_got_notified_for_level_four_completion',
            new_name='is_user_got_notified_for_level_four_completion',
        ),
        migrations.RenameField(
            model_name='z2hcustomers',
            old_name='is_referrer_got_notified_for_level_one_completion',
            new_name='is_user_got_notified_for_level_one_completion',
        ),
        migrations.RenameField(
            model_name='z2hcustomers',
            old_name='is_referrer_got_notified_for_level_three_completion',
            new_name='is_user_got_notified_for_level_three_completion',
        ),
        migrations.RenameField(
            model_name='z2hcustomers',
            old_name='is_referrer_got_notified_for_level_two_completion',
            new_name='is_user_got_notified_for_level_two_completion',
        ),
    ]
