# Generated by Django 4.2.10 on 2024-04-21 12:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Z2HOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hsn_code', models.CharField(blank=True, max_length=64, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('cgst_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('cgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('sgst_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('sgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('igst_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('igst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('gst_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Z2HOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('order_cgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('order_sgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('order_igst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('order_gst_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('order_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('order_status', models.CharField(blank=True, default='pending', max_length=64, null=True)),
                ('order_type', models.CharField(blank=True, default='customer', max_length=64, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_details', models.JSONField(blank=True, default=dict, null=True)),
                ('payment_details', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Z2HPlanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('level_one_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('level_two_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('level_three_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('level_four_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Z2HProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Z2HProductSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.z2hproductcategories')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Z2HProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('discount_type', models.CharField(blank=True, max_length=64, null=True)),
                ('discount_start_date', models.DateTimeField(blank=True, null=True)),
                ('discount_end_date', models.DateTimeField(blank=True, null=True)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.z2hproductsubcategories')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Z2HProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product_image_url', models.CharField(blank=True, max_length=256, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.z2hproducts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
