# Generated by Django 4.2.10 on 2024-03-14 15:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Z2HPlanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('level_one_percentage', models.IntegerField()),
                ('level_two_percentage', models.IntegerField()),
                ('level_three_percentage', models.IntegerField()),
                ('level_four_percentage', models.IntegerField()),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
