# Generated by Django 4.2.10 on 2024-04-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_z2hplandetails_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='z2hplandetails',
            name='level_four_percentage',
        ),
        migrations.RemoveField(
            model_name='z2hplandetails',
            name='level_one_percentage',
        ),
        migrations.RemoveField(
            model_name='z2hplandetails',
            name='level_three_percentage',
        ),
        migrations.RemoveField(
            model_name='z2hplandetails',
            name='level_two_percentage',
        ),
        migrations.AddField(
            model_name='z2hplandetails',
            name='level_four_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='z2hplandetails',
            name='level_one_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='z2hplandetails',
            name='level_three_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='z2hplandetails',
            name='level_two_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='z2hplandetails',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='z2hplandetails',
            name='registration_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
