# Generated by Django 4.2.10 on 2024-04-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_z2hadvertisements'),
    ]

    operations = [
        migrations.AddField(
            model_name='z2hproducts',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
