# Generated by Django 4.2.10 on 2024-04-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_z2hplandetails_level_four_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='z2hplandetails',
            name='registration_fee',
        ),
    ]
