# Generated by Django 4.2.10 on 2024-04-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_z2hproductcategories_z2hproductsubcategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='z2hplandetails',
            name='registration_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
