# Generated by Django 4.2.10 on 2024-05-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_z2hwebpageroles_z2hwebpages'),
    ]

    operations = [
        migrations.AddField(
            model_name='z2hplandetails',
            name='is_flat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='z2hplandetails',
            name='is_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='z2hplandetails',
            name='percentage_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
