# Generated by Django 4.2.10 on 2024-04-14 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_z2hplandetails_registration_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Z2HOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('cgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('sgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('igst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('gst_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('order_status', models.CharField(blank=True, max_length=64, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_remark', models.TextField(blank=True, null=True)),
                ('delivery_details', models.JSONField(blank=True, default=dict, null=True)),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.z2hproducts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
