# Generated by Django 4.2.10 on 2024-05-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_is_flat_z2hplandetails_is_level_four_flat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='z2hplandetails',
            name='level_four_flat_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='z2hplandetails',
            name='level_one_flat_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='z2hplandetails',
            name='level_three_flat_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
