# Generated by Django 4.2.10 on 2024-04-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_z2horders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='z2horders',
            name='delivery_remark',
        ),
        migrations.AddField(
            model_name='z2horders',
            name='payment_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
