# Generated by Django 4.2.10 on 2024-04-14 09:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_z2horders_delivery_remark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='z2horders',
            old_name='cgst_amount',
            new_name='order_cgst_amount',
        ),
        migrations.RenameField(
            model_name='z2horders',
            old_name='gst_total_amount',
            new_name='order_gst_total_amount',
        ),
        migrations.RenameField(
            model_name='z2horders',
            old_name='igst_amount',
            new_name='order_igst_amount',
        ),
        migrations.RenameField(
            model_name='z2horders',
            old_name='sgst_amount',
            new_name='order_sgst_amount',
        ),
        migrations.RenameField(
            model_name='z2horders',
            old_name='total_amount',
            new_name='order_total_amount',
        ),
        migrations.RemoveField(
            model_name='z2horders',
            name='product',
        ),
        migrations.RemoveField(
            model_name='z2horders',
            name='quantity',
        ),
        migrations.AddField(
            model_name='z2horders',
            name='order_type',
            field=models.CharField(blank=True, default='customer', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='z2horders',
            name='order_status',
            field=models.CharField(blank=True, default='pending', max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='Z2HOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hsn_code', models.CharField(blank=True, max_length=64, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('cgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('sgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('igst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('gst_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.z2horders')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.z2hproducts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
