# Generated by Django 4.2.10 on 2024-04-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_cgst_amount_z2horders_order_cgst_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='z2horderitems',
            name='cgst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='z2horderitems',
            name='igst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='z2horderitems',
            name='sgst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
