# Generated by Django 4.2.10 on 2024-05-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_z2horders_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='z2horderitems',
            name='order_item_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='z2horders',
            name='order_status',
            field=models.CharField(blank=True, default='yet_to_be_couriered', max_length=64, null=True),
        ),
    ]
