# Generated by Django 4.2.10 on 2024-06-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_z2horderitems_order_item_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='z2horders',
            name='tds_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='z2horders',
            name='tds_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
