# Generated by Django 4.2.10 on 2024-06-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_z2horders_tds_amount_z2horders_tds_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='z2horders',
            old_name='tds_amount',
            new_name='total_product_price',
        ),
        migrations.RemoveField(
            model_name='z2horders',
            name='tds_percentage',
        ),
    ]
