# Generated by Django 4.2.10 on 2024-06-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_tds_amount_z2horders_total_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='z2hproductcategories',
            name='category_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='z2hproductsubcategories',
            name='sub_category_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
