# Generated by Django 4.2.10 on 2024-06-04 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_z2hproductcategories_category_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='z2hproducts',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.z2hplandetails'),
        ),
    ]
