# Generated by Django 4.2.10 on 2024-06-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_z2hproducts_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='z2hproducts',
            name='product_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
